/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author extends org.jooq.impl.TableImpl<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> {

	private static final long serialVersionUID = 1433089297;

	/**
	 * The reference instance of <code>public.author</code>
	 */
	public static final io.progix.dropwizard.jooq.schema.tables.Author AUTHOR = new io.progix.dropwizard.jooq.schema.tables.Author();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> getRecordType() {
		return io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord.class;
	}

	/**
	 * The column <code>public.author.id</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.author.first_name</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.author.last_name</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>public.author.date_of_birth</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord, java.sql.Date> DATE_OF_BIRTH = createField("date_of_birth", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>public.author.year_of_birth</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord, java.lang.Integer> YEAR_OF_BIRTH = createField("year_of_birth", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.author.distinguished</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord, java.lang.Integer> DISTINGUISHED = createField("distinguished", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.author</code> table reference
	 */
	public Author() {
		this("author", null);
	}

	/**
	 * Create an aliased <code>public.author</code> table reference
	 */
	public Author(java.lang.String alias) {
		this(alias, io.progix.dropwizard.jooq.schema.tables.Author.AUTHOR);
	}

	private Author(java.lang.String alias, org.jooq.Table<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> aliased) {
		this(alias, aliased, null);
	}

	private Author(java.lang.String alias, org.jooq.Table<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.progix.dropwizard.jooq.schema.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord, java.lang.Integer> getIdentity() {
		return io.progix.dropwizard.jooq.schema.Keys.IDENTITY_AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> getPrimaryKey() {
		return io.progix.dropwizard.jooq.schema.Keys.AUTHOR_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord>>asList(io.progix.dropwizard.jooq.schema.Keys.AUTHOR_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.progix.dropwizard.jooq.schema.tables.Author as(java.lang.String alias) {
		return new io.progix.dropwizard.jooq.schema.tables.Author(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.progix.dropwizard.jooq.schema.tables.Author rename(java.lang.String name) {
		return new io.progix.dropwizard.jooq.schema.tables.Author(name, null);
	}
}
