/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author extends org.jooq.impl.TableImpl<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> {

	private static final long serialVersionUID = 975844061;

	/**
	 * The reference instance of <code>PUBLIC.AUTHOR</code>
	 */
	public static final io.progix.dropwizard.jooq.schema.tables.Author AUTHOR = new io.progix.dropwizard.jooq.schema.tables.Author();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> getRecordType() {
		return io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord.class;
	}

	/**
	 * The column <code>PUBLIC.AUTHOR.ID</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.AUTHOR.NAME</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(32672), this, "");

	/**
	 * Create a <code>PUBLIC.AUTHOR</code> table reference
	 */
	public Author() {
		this("AUTHOR", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.AUTHOR</code> table reference
	 */
	public Author(java.lang.String alias) {
		this(alias, io.progix.dropwizard.jooq.schema.tables.Author.AUTHOR);
	}

	private Author(java.lang.String alias, org.jooq.Table<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> aliased) {
		this(alias, aliased, null);
	}

	private Author(java.lang.String alias, org.jooq.Table<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.progix.dropwizard.jooq.schema.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> getPrimaryKey() {
		return io.progix.dropwizard.jooq.schema.Keys.SYS_PK_10093;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord>>asList(io.progix.dropwizard.jooq.schema.Keys.SYS_PK_10093);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.progix.dropwizard.jooq.schema.tables.Author as(java.lang.String alias) {
		return new io.progix.dropwizard.jooq.schema.tables.Author(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.progix.dropwizard.jooq.schema.tables.Author rename(java.lang.String name) {
		return new io.progix.dropwizard.jooq.schema.tables.Author(name, null);
	}
}
