/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book extends org.jooq.impl.TableImpl<io.progix.dropwizard.jooq.schema.tables.records.BookRecord> {

	private static final long serialVersionUID = -928569957;

	/**
	 * The reference instance of <code>public.book</code>
	 */
	public static final io.progix.dropwizard.jooq.schema.tables.Book BOOK = new io.progix.dropwizard.jooq.schema.tables.Book();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.progix.dropwizard.jooq.schema.tables.records.BookRecord> getRecordType() {
		return io.progix.dropwizard.jooq.schema.tables.records.BookRecord.class;
	}

	/**
	 * The column <code>public.book.id</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.book.author_id</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, java.lang.Integer> AUTHOR_ID = createField("author_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.book.title</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(400).nullable(false), this, "");

	/**
	 * The column <code>public.book.published_in</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, java.lang.Integer> PUBLISHED_IN = createField("published_in", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.book.language_id</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, java.lang.Integer> LANGUAGE_ID = createField("language_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.book</code> table reference
	 */
	public Book() {
		this("book", null);
	}

	/**
	 * Create an aliased <code>public.book</code> table reference
	 */
	public Book(java.lang.String alias) {
		this(alias, io.progix.dropwizard.jooq.schema.tables.Book.BOOK);
	}

	private Book(java.lang.String alias, org.jooq.Table<io.progix.dropwizard.jooq.schema.tables.records.BookRecord> aliased) {
		this(alias, aliased, null);
	}

	private Book(java.lang.String alias, org.jooq.Table<io.progix.dropwizard.jooq.schema.tables.records.BookRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.progix.dropwizard.jooq.schema.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, java.lang.Integer> getIdentity() {
		return io.progix.dropwizard.jooq.schema.Keys.IDENTITY_BOOK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookRecord> getPrimaryKey() {
		return io.progix.dropwizard.jooq.schema.Keys.BOOK_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookRecord>>asList(io.progix.dropwizard.jooq.schema.Keys.BOOK_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, ?>>asList(io.progix.dropwizard.jooq.schema.Keys.BOOK__FK_BOOK_AUTHOR, io.progix.dropwizard.jooq.schema.Keys.BOOK__FK_BOOK_LANGUAGE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.progix.dropwizard.jooq.schema.tables.Book as(java.lang.String alias) {
		return new io.progix.dropwizard.jooq.schema.tables.Book(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.progix.dropwizard.jooq.schema.tables.Book rename(java.lang.String name) {
		return new io.progix.dropwizard.jooq.schema.tables.Book(name, null);
	}
}
