/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookStore extends org.jooq.impl.TableImpl<io.progix.dropwizard.jooq.schema.tables.records.BookStoreRecord> {

	private static final long serialVersionUID = 1505263781;

	/**
	 * The reference instance of <code>public.book_store</code>
	 */
	public static final io.progix.dropwizard.jooq.schema.tables.BookStore BOOK_STORE = new io.progix.dropwizard.jooq.schema.tables.BookStore();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.progix.dropwizard.jooq.schema.tables.records.BookStoreRecord> getRecordType() {
		return io.progix.dropwizard.jooq.schema.tables.records.BookStoreRecord.class;
	}

	/**
	 * The column <code>public.book_store.name</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.BookStoreRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(400).nullable(false), this, "");

	/**
	 * Create a <code>public.book_store</code> table reference
	 */
	public BookStore() {
		this("book_store", null);
	}

	/**
	 * Create an aliased <code>public.book_store</code> table reference
	 */
	public BookStore(java.lang.String alias) {
		this(alias, io.progix.dropwizard.jooq.schema.tables.BookStore.BOOK_STORE);
	}

	private BookStore(java.lang.String alias, org.jooq.Table<io.progix.dropwizard.jooq.schema.tables.records.BookStoreRecord> aliased) {
		this(alias, aliased, null);
	}

	private BookStore(java.lang.String alias, org.jooq.Table<io.progix.dropwizard.jooq.schema.tables.records.BookStoreRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.progix.dropwizard.jooq.schema.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookStoreRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookStoreRecord>>asList(io.progix.dropwizard.jooq.schema.Keys.BOOK_STORE_NAME_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.progix.dropwizard.jooq.schema.tables.BookStore as(java.lang.String alias) {
		return new io.progix.dropwizard.jooq.schema.tables.BookStore(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.progix.dropwizard.jooq.schema.tables.BookStore rename(java.lang.String name) {
		return new io.progix.dropwizard.jooq.schema.tables.BookStore(name, null);
	}
}
