/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookToBookStore extends org.jooq.impl.TableImpl<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord> {

	private static final long serialVersionUID = -316218643;

	/**
	 * The reference instance of <code>public.book_to_book_store</code>
	 */
	public static final io.progix.dropwizard.jooq.schema.tables.BookToBookStore BOOK_TO_BOOK_STORE = new io.progix.dropwizard.jooq.schema.tables.BookToBookStore();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord> getRecordType() {
		return io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord.class;
	}

	/**
	 * The column <code>public.book_to_book_store.name</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(400).nullable(false), this, "");

	/**
	 * The column <code>public.book_to_book_store.book_id</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord, java.lang.Integer> BOOK_ID = createField("book_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.book_to_book_store.stock</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord, java.lang.Integer> STOCK = createField("stock", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.book_to_book_store</code> table reference
	 */
	public BookToBookStore() {
		this("book_to_book_store", null);
	}

	/**
	 * Create an aliased <code>public.book_to_book_store</code> table reference
	 */
	public BookToBookStore(java.lang.String alias) {
		this(alias, io.progix.dropwizard.jooq.schema.tables.BookToBookStore.BOOK_TO_BOOK_STORE);
	}

	private BookToBookStore(java.lang.String alias, org.jooq.Table<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord> aliased) {
		this(alias, aliased, null);
	}

	private BookToBookStore(java.lang.String alias, org.jooq.Table<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.progix.dropwizard.jooq.schema.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord> getPrimaryKey() {
		return io.progix.dropwizard.jooq.schema.Keys.BOOK_TO_BOOK_STORE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord>>asList(io.progix.dropwizard.jooq.schema.Keys.BOOK_TO_BOOK_STORE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord, ?>>asList(io.progix.dropwizard.jooq.schema.Keys.BOOK_TO_BOOK_STORE__FK_B2BS_BOOK_STORE, io.progix.dropwizard.jooq.schema.Keys.BOOK_TO_BOOK_STORE__FK_B2BS_BOOK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.progix.dropwizard.jooq.schema.tables.BookToBookStore as(java.lang.String alias) {
		return new io.progix.dropwizard.jooq.schema.tables.BookToBookStore(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.progix.dropwizard.jooq.schema.tables.BookToBookStore rename(java.lang.String name) {
		return new io.progix.dropwizard.jooq.schema.tables.BookToBookStore(name, null);
	}
}
