/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Language extends org.jooq.impl.TableImpl<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord> {

	private static final long serialVersionUID = 369288893;

	/**
	 * The reference instance of <code>public.language</code>
	 */
	public static final io.progix.dropwizard.jooq.schema.tables.Language LANGUAGE = new io.progix.dropwizard.jooq.schema.tables.Language();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord> getRecordType() {
		return io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord.class;
	}

	/**
	 * The column <code>public.language.id</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.language.cd</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord, java.lang.String> CD = createField("cd", org.jooq.impl.SQLDataType.CHAR.length(2).nullable(false), this, "");

	/**
	 * The column <code>public.language.description</code>.
	 */
	public final org.jooq.TableField<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * Create a <code>public.language</code> table reference
	 */
	public Language() {
		this("language", null);
	}

	/**
	 * Create an aliased <code>public.language</code> table reference
	 */
	public Language(java.lang.String alias) {
		this(alias, io.progix.dropwizard.jooq.schema.tables.Language.LANGUAGE);
	}

	private Language(java.lang.String alias, org.jooq.Table<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord> aliased) {
		this(alias, aliased, null);
	}

	private Language(java.lang.String alias, org.jooq.Table<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, io.progix.dropwizard.jooq.schema.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord, java.lang.Integer> getIdentity() {
		return io.progix.dropwizard.jooq.schema.Keys.IDENTITY_LANGUAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord> getPrimaryKey() {
		return io.progix.dropwizard.jooq.schema.Keys.LANGUAGE_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord>>asList(io.progix.dropwizard.jooq.schema.Keys.LANGUAGE_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public io.progix.dropwizard.jooq.schema.tables.Language as(java.lang.String alias) {
		return new io.progix.dropwizard.jooq.schema.tables.Language(alias, this);
	}

	/**
	 * Rename this table
	 */
	public io.progix.dropwizard.jooq.schema.tables.Language rename(java.lang.String name) {
		return new io.progix.dropwizard.jooq.schema.tables.Language(name, null);
	}
}
