/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookToBookStoreDao extends org.jooq.impl.DAOImpl<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord, io.progix.dropwizard.jooq.schema.tables.pojos.BookToBookStore, org.jooq.Record2<java.lang.String, java.lang.Integer>> {

	/**
	 * Create a new BookToBookStoreDao without any configuration
	 */
	public BookToBookStoreDao() {
		super(io.progix.dropwizard.jooq.schema.tables.BookToBookStore.BOOK_TO_BOOK_STORE, io.progix.dropwizard.jooq.schema.tables.pojos.BookToBookStore.class);
	}

	/**
	 * Create a new BookToBookStoreDao with an attached configuration
	 */
	public BookToBookStoreDao(org.jooq.Configuration configuration) {
		super(io.progix.dropwizard.jooq.schema.tables.BookToBookStore.BOOK_TO_BOOK_STORE, io.progix.dropwizard.jooq.schema.tables.pojos.BookToBookStore.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected org.jooq.Record2<java.lang.String, java.lang.Integer> getId(io.progix.dropwizard.jooq.schema.tables.pojos.BookToBookStore object) {
		return compositeKeyRecord(object.getName(), object.getBookId());
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<io.progix.dropwizard.jooq.schema.tables.pojos.BookToBookStore> fetchByName(java.lang.String... values) {
		return fetch(io.progix.dropwizard.jooq.schema.tables.BookToBookStore.BOOK_TO_BOOK_STORE.NAME, values);
	}

	/**
	 * Fetch records that have <code>book_id IN (values)</code>
	 */
	public java.util.List<io.progix.dropwizard.jooq.schema.tables.pojos.BookToBookStore> fetchByBookId(java.lang.Integer... values) {
		return fetch(io.progix.dropwizard.jooq.schema.tables.BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID, values);
	}

	/**
	 * Fetch records that have <code>stock IN (values)</code>
	 */
	public java.util.List<io.progix.dropwizard.jooq.schema.tables.pojos.BookToBookStore> fetchByStock(java.lang.Integer... values) {
		return fetch(io.progix.dropwizard.jooq.schema.tables.BookToBookStore.BOOK_TO_BOOK_STORE.STOCK, values);
	}
}
