/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookDao extends org.jooq.impl.DAOImpl<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, io.progix.dropwizard.jooq.schema.tables.pojos.Book, java.lang.Integer> {

	/**
	 * Create a new BookDao without any configuration
	 */
	public BookDao() {
		super(io.progix.dropwizard.jooq.schema.tables.Book.BOOK, io.progix.dropwizard.jooq.schema.tables.pojos.Book.class);
	}

	/**
	 * Create a new BookDao with an attached configuration
	 */
	public BookDao(org.jooq.Configuration configuration) {
		super(io.progix.dropwizard.jooq.schema.tables.Book.BOOK, io.progix.dropwizard.jooq.schema.tables.pojos.Book.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(io.progix.dropwizard.jooq.schema.tables.pojos.Book object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<io.progix.dropwizard.jooq.schema.tables.pojos.Book> fetchById(java.lang.Integer... values) {
		return fetch(io.progix.dropwizard.jooq.schema.tables.Book.BOOK.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public io.progix.dropwizard.jooq.schema.tables.pojos.Book fetchOneById(java.lang.Integer value) {
		return fetchOne(io.progix.dropwizard.jooq.schema.tables.Book.BOOK.ID, value);
	}

	/**
	 * Fetch records that have <code>author_id IN (values)</code>
	 */
	public java.util.List<io.progix.dropwizard.jooq.schema.tables.pojos.Book> fetchByAuthorId(java.lang.Integer... values) {
		return fetch(io.progix.dropwizard.jooq.schema.tables.Book.BOOK.AUTHOR_ID, values);
	}

	/**
	 * Fetch records that have <code>title IN (values)</code>
	 */
	public java.util.List<io.progix.dropwizard.jooq.schema.tables.pojos.Book> fetchByTitle(java.lang.String... values) {
		return fetch(io.progix.dropwizard.jooq.schema.tables.Book.BOOK.TITLE, values);
	}

	/**
	 * Fetch records that have <code>published_in IN (values)</code>
	 */
	public java.util.List<io.progix.dropwizard.jooq.schema.tables.pojos.Book> fetchByPublishedIn(java.lang.Integer... values) {
		return fetch(io.progix.dropwizard.jooq.schema.tables.Book.BOOK.PUBLISHED_IN, values);
	}

	/**
	 * Fetch records that have <code>language_id IN (values)</code>
	 */
	public java.util.List<io.progix.dropwizard.jooq.schema.tables.pojos.Book> fetchByLanguageId(java.lang.Integer... values) {
		return fetch(io.progix.dropwizard.jooq.schema.tables.Book.BOOK.LANGUAGE_ID, values);
	}
}
