/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LanguageDao extends org.jooq.impl.DAOImpl<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord, io.progix.dropwizard.jooq.schema.tables.pojos.Language, java.lang.Integer> {

	/**
	 * Create a new LanguageDao without any configuration
	 */
	public LanguageDao() {
		super(io.progix.dropwizard.jooq.schema.tables.Language.LANGUAGE, io.progix.dropwizard.jooq.schema.tables.pojos.Language.class);
	}

	/**
	 * Create a new LanguageDao with an attached configuration
	 */
	public LanguageDao(org.jooq.Configuration configuration) {
		super(io.progix.dropwizard.jooq.schema.tables.Language.LANGUAGE, io.progix.dropwizard.jooq.schema.tables.pojos.Language.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(io.progix.dropwizard.jooq.schema.tables.pojos.Language object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<io.progix.dropwizard.jooq.schema.tables.pojos.Language> fetchById(java.lang.Integer... values) {
		return fetch(io.progix.dropwizard.jooq.schema.tables.Language.LANGUAGE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public io.progix.dropwizard.jooq.schema.tables.pojos.Language fetchOneById(java.lang.Integer value) {
		return fetchOne(io.progix.dropwizard.jooq.schema.tables.Language.LANGUAGE.ID, value);
	}

	/**
	 * Fetch records that have <code>cd IN (values)</code>
	 */
	public java.util.List<io.progix.dropwizard.jooq.schema.tables.pojos.Language> fetchByCd(java.lang.String... values) {
		return fetch(io.progix.dropwizard.jooq.schema.tables.Language.LANGUAGE.CD, values);
	}

	/**
	 * Fetch records that have <code>description IN (values)</code>
	 */
	public java.util.List<io.progix.dropwizard.jooq.schema.tables.pojos.Language> fetchByDescription(java.lang.String... values) {
		return fetch(io.progix.dropwizard.jooq.schema.tables.Language.LANGUAGE.DESCRIPTION, values);
	}
}
