/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema;

/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord, java.lang.Integer> IDENTITY_AUTHOR = Identities0.IDENTITY_AUTHOR;
	public static final org.jooq.Identity<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, java.lang.Integer> IDENTITY_BOOK = Identities0.IDENTITY_BOOK;
	public static final org.jooq.Identity<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord, java.lang.Integer> IDENTITY_LANGUAGE = Identities0.IDENTITY_LANGUAGE;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> AUTHOR_PKEY = UniqueKeys0.AUTHOR_PKEY;
	public static final org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookRecord> BOOK_PKEY = UniqueKeys0.BOOK_PKEY;
	public static final org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookStoreRecord> BOOK_STORE_NAME_KEY = UniqueKeys0.BOOK_STORE_NAME_KEY;
	public static final org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord> BOOK_TO_BOOK_STORE_PKEY = UniqueKeys0.BOOK_TO_BOOK_STORE_PKEY;
	public static final org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord> LANGUAGE_PKEY = UniqueKeys0.LANGUAGE_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> BOOK__FK_BOOK_AUTHOR = ForeignKeys0.BOOK__FK_BOOK_AUTHOR;
	public static final org.jooq.ForeignKey<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord> BOOK__FK_BOOK_LANGUAGE = ForeignKeys0.BOOK__FK_BOOK_LANGUAGE;
	public static final org.jooq.ForeignKey<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord, io.progix.dropwizard.jooq.schema.tables.records.BookStoreRecord> BOOK_TO_BOOK_STORE__FK_B2BS_BOOK_STORE = ForeignKeys0.BOOK_TO_BOOK_STORE__FK_B2BS_BOOK_STORE;
	public static final org.jooq.ForeignKey<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord, io.progix.dropwizard.jooq.schema.tables.records.BookRecord> BOOK_TO_BOOK_STORE__FK_B2BS_BOOK = ForeignKeys0.BOOK_TO_BOOK_STORE__FK_B2BS_BOOK;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord, java.lang.Integer> IDENTITY_AUTHOR = createIdentity(io.progix.dropwizard.jooq.schema.tables.Author.AUTHOR, io.progix.dropwizard.jooq.schema.tables.Author.AUTHOR.ID);
		public static org.jooq.Identity<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, java.lang.Integer> IDENTITY_BOOK = createIdentity(io.progix.dropwizard.jooq.schema.tables.Book.BOOK, io.progix.dropwizard.jooq.schema.tables.Book.BOOK.ID);
		public static org.jooq.Identity<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord, java.lang.Integer> IDENTITY_LANGUAGE = createIdentity(io.progix.dropwizard.jooq.schema.tables.Language.LANGUAGE, io.progix.dropwizard.jooq.schema.tables.Language.LANGUAGE.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> AUTHOR_PKEY = createUniqueKey(io.progix.dropwizard.jooq.schema.tables.Author.AUTHOR, io.progix.dropwizard.jooq.schema.tables.Author.AUTHOR.ID);
		public static final org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookRecord> BOOK_PKEY = createUniqueKey(io.progix.dropwizard.jooq.schema.tables.Book.BOOK, io.progix.dropwizard.jooq.schema.tables.Book.BOOK.ID);
		public static final org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookStoreRecord> BOOK_STORE_NAME_KEY = createUniqueKey(io.progix.dropwizard.jooq.schema.tables.BookStore.BOOK_STORE, io.progix.dropwizard.jooq.schema.tables.BookStore.BOOK_STORE.NAME);
		public static final org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord> BOOK_TO_BOOK_STORE_PKEY = createUniqueKey(io.progix.dropwizard.jooq.schema.tables.BookToBookStore.BOOK_TO_BOOK_STORE, io.progix.dropwizard.jooq.schema.tables.BookToBookStore.BOOK_TO_BOOK_STORE.NAME, io.progix.dropwizard.jooq.schema.tables.BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID);
		public static final org.jooq.UniqueKey<io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord> LANGUAGE_PKEY = createUniqueKey(io.progix.dropwizard.jooq.schema.tables.Language.LANGUAGE, io.progix.dropwizard.jooq.schema.tables.Language.LANGUAGE.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, io.progix.dropwizard.jooq.schema.tables.records.AuthorRecord> BOOK__FK_BOOK_AUTHOR = createForeignKey(io.progix.dropwizard.jooq.schema.Keys.AUTHOR_PKEY, io.progix.dropwizard.jooq.schema.tables.Book.BOOK, io.progix.dropwizard.jooq.schema.tables.Book.BOOK.AUTHOR_ID);
		public static final org.jooq.ForeignKey<io.progix.dropwizard.jooq.schema.tables.records.BookRecord, io.progix.dropwizard.jooq.schema.tables.records.LanguageRecord> BOOK__FK_BOOK_LANGUAGE = createForeignKey(io.progix.dropwizard.jooq.schema.Keys.LANGUAGE_PKEY, io.progix.dropwizard.jooq.schema.tables.Book.BOOK, io.progix.dropwizard.jooq.schema.tables.Book.BOOK.LANGUAGE_ID);
		public static final org.jooq.ForeignKey<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord, io.progix.dropwizard.jooq.schema.tables.records.BookStoreRecord> BOOK_TO_BOOK_STORE__FK_B2BS_BOOK_STORE = createForeignKey(io.progix.dropwizard.jooq.schema.Keys.BOOK_STORE_NAME_KEY, io.progix.dropwizard.jooq.schema.tables.BookToBookStore.BOOK_TO_BOOK_STORE, io.progix.dropwizard.jooq.schema.tables.BookToBookStore.BOOK_TO_BOOK_STORE.NAME);
		public static final org.jooq.ForeignKey<io.progix.dropwizard.jooq.schema.tables.records.BookToBookStoreRecord, io.progix.dropwizard.jooq.schema.tables.records.BookRecord> BOOK_TO_BOOK_STORE__FK_B2BS_BOOK = createForeignKey(io.progix.dropwizard.jooq.schema.Keys.BOOK_PKEY, io.progix.dropwizard.jooq.schema.tables.BookToBookStore.BOOK_TO_BOOK_STORE, io.progix.dropwizard.jooq.schema.tables.BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID);
	}
}
