/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema;

/**
 * Convenience access to all sequences in public
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.author_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> AUTHOR_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("author_id_seq", io.progix.dropwizard.jooq.schema.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.book_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> BOOK_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("book_id_seq", io.progix.dropwizard.jooq.schema.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

	/**
	 * The sequence <code>public.language_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> LANGUAGE_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("language_id_seq", io.progix.dropwizard.jooq.schema.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
