/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema;

/**
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.AUTHOR
	 */
	public static final io.progix.dropwizard.jooq.schema.tables.Author AUTHOR = io.progix.dropwizard.jooq.schema.tables.Author.AUTHOR;
}
