/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author implements java.io.Serializable {

	private static final long serialVersionUID = 1709205953;

	private final java.lang.Integer id;
	private final java.lang.String  name;

	public Author(
		java.lang.Integer id,
		java.lang.String  name
	) {
		this.id = id;
		this.name = name;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public java.lang.String getName() {
		return this.name;
	}
}
