/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author implements java.io.Serializable {

	private static final long serialVersionUID = -1697766702;

	private java.lang.Integer id;
	private java.lang.String  name;

	public Author() {}

	public Author(
		java.lang.Integer id,
		java.lang.String  name
	) {
		this.id = id;
		this.name = name;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public Author setId(java.lang.Integer id) {
		this.id = id;
		return this;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public Author setName(java.lang.String name) {
		this.name = name;
		return this;
	}
}
