/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookToBookStore implements java.io.Serializable {

	private static final long serialVersionUID = -1163052713;

	private final java.lang.String  name;
	private final java.lang.Integer bookId;
	private final java.lang.Integer stock;

	public BookToBookStore(
		java.lang.String  name,
		java.lang.Integer bookId,
		java.lang.Integer stock
	) {
		this.name = name;
		this.bookId = bookId;
		this.stock = stock;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public java.lang.Integer getBookId() {
		return this.bookId;
	}

	public java.lang.Integer getStock() {
		return this.stock;
	}
}
