/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements java.io.Serializable {

	private static final long serialVersionUID = 1660312031;

	private final java.lang.Integer id;
	private final java.lang.Integer authorId;
	private final java.lang.String  title;
	private final java.lang.Integer publishedIn;
	private final java.lang.Integer languageId;

	public Book(
		java.lang.Integer id,
		java.lang.Integer authorId,
		java.lang.String  title,
		java.lang.Integer publishedIn,
		java.lang.Integer languageId
	) {
		this.id = id;
		this.authorId = authorId;
		this.title = title;
		this.publishedIn = publishedIn;
		this.languageId = languageId;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public java.lang.Integer getAuthorId() {
		return this.authorId;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public java.lang.Integer getPublishedIn() {
		return this.publishedIn;
	}

	public java.lang.Integer getLanguageId() {
		return this.languageId;
	}
}
