/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Language implements java.io.Serializable {

	private static final long serialVersionUID = -1525877908;

	private final java.lang.Integer id;
	private final java.lang.String  cd;
	private final java.lang.String  description;

	public Language(
		java.lang.Integer id,
		java.lang.String  cd,
		java.lang.String  description
	) {
		this.id = id;
		this.cd = cd;
		this.description = description;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public java.lang.String getCd() {
		return this.cd;
	}

	public java.lang.String getDescription() {
		return this.description;
	}
}
