/**
 * This class is generated by jOOQ
 */
package io.progix.dropwizard.jooq.schema.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookStoreRecord extends org.jooq.impl.TableRecordImpl<io.progix.dropwizard.jooq.schema.tables.records.BookStoreRecord> implements org.jooq.Record1<java.lang.String> {

	private static final long serialVersionUID = -236814321;

	/**
	 * Setter for <code>public.book_store.name</code>.
	 */
	public BookStoreRecord setName(java.lang.String value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.book_store.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> fieldsRow() {
		return (org.jooq.Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> valuesRow() {
		return (org.jooq.Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return io.progix.dropwizard.jooq.schema.tables.BookStore.BOOK_STORE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookStoreRecord value1(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookStoreRecord values(java.lang.String value1) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BookStoreRecord
	 */
	public BookStoreRecord() {
		super(io.progix.dropwizard.jooq.schema.tables.BookStore.BOOK_STORE);
	}

	/**
	 * Create a detached, initialised BookStoreRecord
	 */
	public BookStoreRecord(java.lang.String name) {
		super(io.progix.dropwizard.jooq.schema.tables.BookStore.BOOK_STORE);

		setValue(0, name);
	}
}
